### ISSUE TITLE
Adding a new user to the database from the front end.

### ISSUE THREAD

**Issue by techiecheckie** [techiecheckie/OBET#1]
In the command line we can appropriately add a user to the DB. It returns an error if there is an issue with the object validation from MongoEngine, which won't allow objects not fitting the schema described into the DB at all. There is also form validation which seems to work on the command line.

But from the front end, we can search the DB and pull info, but we cannot save something to the DB, providing a server error (with no details :().

**Comment by coilysiren** [comment]
`python hello.py runserver -dr` to get flask to give you error messages
