### ISSUE TITLE
Making working embedded records in the User and Lit objects.

### ISSUE THREAD

**Issue by techiecheckie** [techiecheckie/OBET#13]
The client wants to be able to look at a User profile and see the last n posts they edited (potentially with links to those posts) and when, and look at a Lit page and see when the last n edits were done and by which user.

The basics are already commented out in the schema, and they make use of Mongo's embedded document property, which allows you to store information associated with an object without needing a separate collection. (Obviously, the long, ugly option is to make tables and then grab from them, but let's try to use what we're given.)

This will also require use of the datetime library. Information on this can be gotten from the provided Flask web dev book.

**Comment by jwu130** [comment]
I'll work on this one

**Comment by jwu130** [comment]
Fixed and deployed

**Comment by jwu130** [comment]
Time zone in the date field is utc. Changing it to est... Will redeploy the change
