### ISSUE TITLE
Enforce three required fields for Literature, and implement two dropdowns

### ISSUE THREAD

**Issue by jwu130** [techiecheckie/OBET#22]
"REQUIRED FIELDS:

OBET should not accept an entry unless the following three fields are filled:
Reference Type
Title
Primary Field

CLOSED FIELDS
The following two fields can have only specific values; thus a drop-down list is best:

Ten values for "Reference Type":
Book Section
Edited Book
Journal Article
Journal Issue
Magazine Article
Media
Newspaper Article
Report
Thesis
Website    

Eight values for "Primary Field" and "Secondary Field":
Philosophy/Ethics/Theology
Anthropology/Psychology/Sociology
History/Politics/Law
Agriculture/Energy/Industry
Animal Science/Welfare
Ecology/Conservation
Nature Writing/Art/Literary Criticism
Education/Living    " - David Lahti

**Comment by techiecheckie** [comment]
I'm working on this now. Do note that after I complete this and submit it, it will be necessary to refresh the database so new objects can include these.

**Comment by jwu130** [comment]
Should be implemented now
