### ISSUE TITLE
Separate code from configuration

### ISSUE THREAD

**Issue by coilysiren** [techiecheckie/OBET#3]
ie. move the dozen or so `app.config` lines into their own file, a `.env` file

**Comment by techiecheckie** [comment]
I was gonna do this after all the code worked, lol.

**Comment by coilysiren** [comment]
I've done it a dozen times, can do it after I'm done trying to ask ppl out on dates

**Comment by techiecheckie** [comment]
Oh u :P
get ur bewty on
There's a bunch of stuff in general I planned to leave until after the code worked. I generally play that way: Make sure code does the thing, then get pretty afterward.

**Comment by coilysiren** [comment]
Something I forgot to add to the PR is that you'll need to run

```
$ cp .env-example .env
```

To copy over the new environment variables, then add your stuff to `.env` (ie. passwords and such)
