### ISSUE TITLE
MAIL_USERNAME and MAIL_PASSWORD cannot be read from environment.

### ISSUE THREAD

**Issue by techiecheckie** [techiecheckie/OBET#8]
It's fine if you put them straight in, but I can't get them to validate otherwise.

**Comment by coilysiren** [comment]
Describe the issue in detail. Did you put them inside .env and print the contents of dotenv.parse_env ?

**Comment by techiecheckie** [comment]
I didn't try that yet, I was using my original config. I'll try that next, after some sleep. >_>
