### ISSUE TITLE
Method not allowed when trying to addLit.

### ISSUE THREAD

**Issue by techiecheckie** [techiecheckie/OBET#9]
For some reason the DB sends me a 405 error, telling me that the addLit function is not allowed despite only having a "login_required" tag (and I'm logged in). What's going wrong? :(

(For reference, logging in and out works and they require the same tag.)

**Comment by coilysiren** [comment]
Screenshot and / or copy paste the traceback for me?

Also, what is it that you were trying to do? (so I can go do it myself)

**Comment by coilysiren** [comment]
Copy paste is better, actually

**Comment by techiecheckie** [comment]
Okay, so I pull the site up, log in, which makes the "add lit" function available to the user (in the top corner you'll see it). I try to add a new piece of lit through the GUI available when you click there.

It gives _no_ traceback. The DB gives a very boring standard 405 error, and the site reroutes to a page that says the method isn't allowed for the given URL.

**Comment by coilysiren** [comment]
I don't have a copy of the site up right now, can you link me to the addlit function?

**Comment by techiecheckie** [comment]
https://github.com/techiecheckie/OBET/blob/master/app/main/views.py
hit ctrl+f addLit

**Comment by coilysiren** [comment]
Alright, link the line next time though, like so: https://github.com/techiecheckie/OBET/blob/master/app/main/views.py#L116

**Comment by techiecheckie** [comment]
Did not know you could do that, but got it.

**Comment by coilysiren** [comment]
So when doing anything that has to do with routing issues, I use a function that watches and prints all the requests sent to the flask server. It looks like this:

```
app.before_request(_before_request)

def _before_request():
    if not flask.request.endpoint in ['static', 'base_static']:
        print('('+flask_login.current_user['username']+') '+flask.request.method+' '+str(flask.request.path)+' endpoint '+str(flask.request.endpoint)+'()')
```

This will likely not solve your case, but it's an immensely valuable tool

(I copy pasted that straight from Quirell, so there's some fluff there)

**Comment by coilysiren** [comment]
Other things:

A logger would be great here

```
import logging, sys
logging.basicConfig(stream=sys.stdout)
LOG = logging.getLogger(__name__)
LOG.setLevel(logging.INFO)
```

and then

```
LOG.info('something broke')
```

to use

**Comment by coilysiren** [comment]
And instead of

```
from flask import flash
```

Do

```
import flask
def flash(text):
    LOG.info(text)
    flask.flash(text)
```

Changed the import just to avoid namespace collision
